### ISSUE TITLE
Getting a TypeError when calling Payment.objects.create()

### ISSUE THREAD

**Issue by Nirpesh87** [101Loop/drf-instamojo#9]
**TypeError at /order/paymentview1/**
Got a `TypeError` when calling `Payment.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Payment.objects.create()`. You may need to make the field read-only, or override the PaymentSerializer.create() method to handle this correctly.
Original exception was:
 ```
Traceback (most recent call last):
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\rest_framework\serializers.py", line 948, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\django\dispatch\dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\django\dispatch\dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  **File "C:\Users\NIRPESH\AppData\Local\Programs\Python\Python36\lib\site-packages\drf_instamojo\signals\handlers.py", line 35, in payment_record_handler
    if payment_request_imojo.get('modified_at') > pr.modified_at:
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'**
```

**Comment by sumit4613** [comment]
@Nirpesh87 According to the traceback here, the reason you're getting `TypeError` is because `payment_request_imojo.get('modified_at')` here returns **str** and not **datetime.datetime**. And you can't compare different types. Also, I'm not sure why this is happening, if you can show me the code which is causing this maybe I can help in this issue.

Please let us know the steps to reproduce this. I'll try to reproduce it myself. 

Thanks.

**Comment by iamhssingh** [comment]
@sumit4613 We will have to fix this piece of code. Looks like `instamojo` library has been updated or either this was not ever run. You are point-blank on the RCA. Can you raise a PR for this fix?

Also, let's start building test cases on this.

**Comment by Nirpesh87** [comment]
> @Nirpesh87 According to the traceback here, the reason you're getting `TypeError` is because `payment_request_imojo.get('modified_at')` here returns **str** and not **datetime.datetime**. And you can't compare different types. Also, I'm not sure why it returns **str**, if you can show me your code which is causing this maybe I can help in this issue.
> 
> Please let us know the steps to reproduce this. I'll try to reproduce it myself.
> 
> Thanks.

@sumit4613 , should i create a different view for PaymentSerializer to save payment record?

**Comment by sumit4613** [comment]
@Nirpesh87 According to the traceback that was shared by you. The problem isn't in View or Serializer. There's some issue in signal which was called when saving `Payment` object. I'll have to look why `payment_request_imojo.get('modified_at')` is returning **str** rather than **datetime.datetime**. As @iamhssingh suggested maybe instamojo have updated their library or there's some issue in this code. I'll have to debug this and will raise a PR for this issue. 

If you can fix this issue, please let us know or raise a PR with your changes.

Thanks!

**Comment by Nirpesh87** [comment]
Waiting for this bug to be fixed  :(

**Comment by sumit4613** [comment]
@Nirpesh87 We're working on the issue, we'll release a version of this library in a day or two. So please be patient.
